# Generated by Django 5.1.6 on 2025-02-22 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_organizer'),
        ('ticket', '0002_remove_ticket_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='event.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Gold', 'Gold'), ('VIP', 'VIP')], default='Normal', max_length=100),
        ),
    ]
